# Generated by Django 4.2.3 on 2023-07-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_created=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploader_ip', models.GenericIPAddressField()),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
