# Generated by Django 4.2.3 on 2023-07-30 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_alter_uploadedimage_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
